;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="AI.NPC.Minion.Melee",DevComment="근거리 미니언 태그")
GameplayTagList=(Tag="AI.NPC.Minion.Range",DevComment="원거리 미니언 태그")
GameplayTagList=(Tag="AI.NPC.Minion.Seige",DevComment="공성 미니언 태그")
GameplayTagList=(Tag="AI.NPC.Minion.Super",DevComment="슈퍼 미니언 태그")
GameplayTagList=(Tag="AI.NPC.Stat.Health",DevComment="Health 스탯 태그")
GameplayTagList=(Tag="AI.NPC.Stat.Attack",DevComment="Attack 스탯 태그")
GameplayTagList=(Tag="AI.NPC.Stat.Defense",DevComment="Defense 스탯 태그")
GameplayTagList=(Tag="AI.NPC.Stat.Speed",DevComment="Speed 스탯 태그")
GameplayTagList=(Tag="AI.NPC.State.Dead",DevComment="Npc 사망 태그")
