;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagRedirects=(OldTagName="GameplayCue.Sparrow.SkillE",NewTagName="GameplayCue.Sparrow.SkillE.Hit")
GameplayTagRedirects=(OldTagName="GameplayCue.Sparrow.SkillE_End",NewTagName="GameplayCue.Sparrow.SkillE.End")
GameplayTagRedirects=(OldTagName="GameplayCue.Sparrow.SkillQ",NewTagName="GameplayCue.Sparrow.SkillQ.Hit")
GameplayTagRedirects=(OldTagName="GameplayCue.Sparrow.SkillQ_End",NewTagName="GameplayCue.Sparrow.SkillQ.End")
GameplayTagRedirects=(OldTagName="GameplayCue.Sparrow.SkillQ_Targeting",NewTagName="GameplayCue.Sparrow.SkillQ.Targeting")
GameplayTagRedirects=(OldTagName="GameplayCue.Sparrow.SkillR",NewTagName="GameplayCue.Sparrow.SkillR.Hit")
GameplayTagRedirects=(OldTagName="GameplayCue.Sparrow.SkillR_Buff",NewTagName="GameplayCue.Sparrow.SkillR.Buff")
GameplayTagRedirects=(OldTagName="GameplayCue.Sparrow.SkillR_Camera",NewTagName="GameplayCue.Sparrow.SkillR.Camera")
GameplayTagRedirects=(OldTagName="GameplayCue.Sparrow.SkillR_Start",NewTagName="GameplayCue.Sparrow.SkillR.Start")
GameplayTagRedirects=(OldTagName="GameplayCue.Sparrow.NormalBullet",NewTagName="GameplayCue.Sparrow.Attack.Hit")
GameplayTagList=(Tag="GameplayCue.Sparrow.Attack.Hit",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillE.End",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillE.Hit",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillQ.End",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillQ.Hit",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillQ.Targeting",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillR.Buff",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillR.Camera",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillR.Hit",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillR.Start",DevComment="")

