;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="GameplayCue.Sparrow.NormalBullet",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillE",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillE_End",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillQ",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillQ_End",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillQ_Targeting",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillR",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillR_Buff",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillR_Camera",DevComment="")
GameplayTagList=(Tag="GameplayCue.Sparrow.SkillR_Start",DevComment="")

