;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Character.State.Charging",DevComment="")
GameplayTagList=(Tag="Character.State.SparrowUlt",DevComment="")
GameplayTagList=(Tag="Event.Character.SpawnBullet",DevComment="")

