;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Character.Ability.SkillE",DevComment="")
+GameplayTagList=(Tag="Character.Ability.SkillQ",DevComment="")
+GameplayTagList=(Tag="Character.Ability.SkillR",DevComment="")
+GameplayTagList=(Tag="Character.State.Airborne",DevComment="")
+GameplayTagList=(Tag="Character.State.Attaking",DevComment="")
+GameplayTagList=(Tag="Character.State.Jumping",DevComment="")
+GameplayTagList=(Tag="Character.State.Spawning",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill.E",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill.Q",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill.R",DevComment="")
+GameplayTagList=(Tag="Event.Aurora.DashStart",DevComment="")
+GameplayTagList=(Tag="Event.Aurora.DashStop",DevComment="")
+GameplayTagList=(Tag="Event.Character.ComboWindowClosed",DevComment="")
+GameplayTagList=(Tag="Event.Character.ComboWindowOpened",DevComment="")
+GameplayTagList=(Tag="Event.Character.HitCheck",DevComment="")
+GameplayTagList=(Tag="Event.Character.HitResult",DevComment="")
+GameplayTagList=(Tag="Event.Character.HitResult.BasicAttack",DevComment="")
+GameplayTagList=(Tag="Event.Character.HitResult.SkillE",DevComment="")
+GameplayTagList=(Tag="Event.Character.HitResult.SkillQ",DevComment="")
+GameplayTagList=(Tag="Event.Character.HitResult.SkillR",DevComment="")
+GameplayTagList=(Tag="Event.Character.StartNextCombo",DevComment="")

